import os
import django
import logging

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bookstore.settings')
django.setup()

from books.models import Book, Review, Order, UserProfile
from django.contrib.auth.models import User

# Set up logger
logger = logging.getLogger(__name__)

# Create sample books
books_data = [
    {'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald', 'genre': 'Fiction', 'category': 'Classic', 'price': 12.99, 'rating': 4.5, 'stock': 50, 'description': 'A classic American novel about the Jazz Age.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671.jpg'},
    {'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'genre': 'Fiction', 'category': 'Classic', 'price': 14.99, 'rating': 4.8, 'stock': 30, 'description': 'A powerful story about racial injustice and childhood.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg'},
    {'title': '1984', 'author': 'George Orwell', 'genre': 'Dystopian', 'category': 'Science Fiction', 'price': 13.99, 'rating': 4.6, 'stock': 40, 'description': 'A dystopian novel about totalitarianism.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1532714506i/40961427.jpg'},
    {'title': 'Pride and Prejudice', 'author': 'Jane Austen', 'genre': 'Romance', 'category': 'Classic', 'price': 11.99, 'rating': 4.7, 'stock': 25, 'description': 'A romantic novel about manners and marriage.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg'},
    {'title': 'The Catcher in the Rye', 'author': 'J.D. Salinger', 'genre': 'Fiction', 'category': 'Coming of Age', 'price': 10.99, 'rating': 4.2, 'stock': 35, 'description': 'A controversial novel about teenage angst.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg'},
    {'title': 'Harry Potter and the Sorcerer\'s Stone', 'author': 'J.K. Rowling', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 15.99, 'rating': 4.9, 'stock': 60, 'description': 'The first book in the magical Harry Potter series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1170803558i/3.jpg'},
    {'title': 'The Hobbit', 'author': 'J.R.R. Tolkien', 'genre': 'Fantasy', 'category': 'Adventure', 'price': 16.99, 'rating': 4.8, 'stock': 45, 'description': 'A fantasy adventure about Bilbo Baggins.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg'},
    {'title': 'Dune', 'author': 'Frank Herbert', 'genre': 'Science Fiction', 'category': 'Epic', 'price': 18.99, 'rating': 4.7, 'stock': 20, 'description': 'A science fiction epic set on the desert planet Arrakis.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg'},
    {'title': 'The Lord of the Rings', 'author': 'J.R.R. Tolkien', 'genre': 'Fantasy', 'category': 'Epic', 'price': 25.99, 'rating': 4.9, 'stock': 15, 'description': 'The epic fantasy trilogy about Middle-earth.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg'},
    {'title': 'Neuromancer', 'author': 'William Gibson', 'genre': 'Science Fiction', 'category': 'Cyberpunk', 'price': 14.99, 'rating': 4.3, 'stock': 28, 'description': 'A groundbreaking cyberpunk novel.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554133629i/22328.jpg'},
    {'title': 'The Alchemist', 'author': 'Paulo Coelho', 'genre': 'Fiction', 'category': 'Philosophy', 'price': 13.49, 'rating': 4.4, 'stock': 55, 'description': 'A philosophical novel about following your dreams.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654371463i/18144590.jpg'},
    {'title': 'Sapiens: A Brief History of Humankind', 'author': 'Yuval Noah Harari', 'genre': 'Non-Fiction', 'category': 'History', 'price': 19.99, 'rating': 4.6, 'stock': 40, 'description': 'A sweeping narrative of human history.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1595674533i/23692271.jpg'},
    {'title': 'The Midnight Library', 'author': 'Matt Haig', 'genre': 'Fiction', 'category': 'Fantasy', 'price': 16.99, 'rating': 4.5, 'stock': 35, 'description': 'A novel about the infinite possibilities of life.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190253i/52578297.jpg'},
    {'title': 'Atomic Habits', 'author': 'James Clear', 'genre': 'Non-Fiction', 'category': 'Self-Help', 'price': 17.99, 'rating': 4.7, 'stock': 50, 'description': 'A guide to building good habits and breaking bad ones.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg'},
    {'title': 'The Seven Husbands of Evelyn Hugo', 'author': 'Taylor Jenkins Reid', 'genre': 'Fiction', 'category': 'Romance', 'price': 15.49, 'rating': 4.8, 'stock': 45, 'description': 'A captivating story of a Hollywood icon.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1617129677i/32620332.jpg'},
    {'title': 'Educated', 'author': 'Tara Westover', 'genre': 'Non-Fiction', 'category': 'Memoir', 'price': 14.99, 'rating': 4.6, 'stock': 30, 'description': 'A memoir about education and self-discovery.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg'},
    {'title': 'The Silent Patient', 'author': 'Alex Michaelides', 'genre': 'Thriller', 'category': 'Mystery', 'price': 12.99, 'rating': 4.3, 'stock': 40, 'description': 'A psychological thriller about a woman who stops speaking.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1668782119i/40097951.jpg'},
    {'title': 'Where the Crawdads Sing', 'author': 'Delia Owens', 'genre': 'Fiction', 'category': 'Mystery', 'price': 16.49, 'rating': 4.7, 'stock': 55, 'description': 'A mystery set in the marshes of North Carolina.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1582135294i/36809135.jpg'},
    {'title': 'The Subtle Art of Not Giving a F*ck', 'author': 'Mark Manson', 'genre': 'Non-Fiction', 'category': 'Self-Help', 'price': 15.99, 'rating': 4.2, 'stock': 60, 'description': 'A counterintuitive approach to living a good life.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1465761302i/28257707.jpg'},
    {'title': 'Circe', 'author': 'Madeline Miller', 'genre': 'Fantasy', 'category': 'Mythology', 'price': 17.99, 'rating': 4.6, 'stock': 35, 'description': 'A reimagining of the story of Circe from Greek mythology.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1565909496i/35959740.jpg'},
    {'title': 'The Name of the Wind', 'author': 'Patrick Rothfuss', 'genre': 'Fantasy', 'category': 'Epic', 'price': 18.99, 'rating': 4.8, 'stock': 40, 'description': 'The first book in the Kingkiller Chronicle series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1270352123i/1869.jpg'},
    {'title': 'The Wise Man\'s Fear', 'author': 'Patrick Rothfuss', 'genre': 'Fantasy', 'category': 'Epic', 'price': 19.99, 'rating': 4.7, 'stock': 35, 'description': 'The second book in the Kingkiller Chronicle.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1452624392i/1215032.jpg'},
    {'title': 'The Martian', 'author': 'Andy Weir', 'genre': 'Science Fiction', 'category': 'Adventure', 'price': 14.99, 'rating': 4.6, 'stock': 50, 'description': 'A survival story on Mars.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1413706054i/18007564.jpg'},
    {'title': 'Ready Player One', 'author': 'Ernest Cline', 'genre': 'Science Fiction', 'category': 'Adventure', 'price': 13.99, 'rating': 4.5, 'stock': 45, 'description': 'A virtual reality adventure.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1500930947i/9969571.jpg'},
    {'title': 'The Hitchhiker\'s Guide to the Galaxy', 'author': 'Douglas Adams', 'genre': 'Science Fiction', 'category': 'Comedy', 'price': 12.99, 'rating': 4.4, 'stock': 55, 'description': 'A comedic science fiction classic.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1559986157i/11.jpg'},
    {'title': 'Ender\'s Game', 'author': 'Orson Scott Card', 'genre': 'Science Fiction', 'category': 'Young Adult', 'price': 11.99, 'rating': 4.6, 'stock': 40, 'description': 'A story of a gifted child trained for war.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1408303130i/375802.jpg'},
    {'title': 'Foundation', 'author': 'Isaac Asimov', 'genre': 'Science Fiction', 'category': 'Epic', 'price': 15.99, 'rating': 4.5, 'stock': 30, 'description': 'The foundation of the Galactic Empire.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1417900846i/29579.jpg'},
    {'title': 'I, Robot', 'author': 'Isaac Asimov', 'genre': 'Science Fiction', 'category': 'Short Stories', 'price': 13.99, 'rating': 4.3, 'stock': 35, 'description': 'A collection of robot stories.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386924461i/41804.jpg'},
    {'title': 'The Left Hand of Darkness', 'author': 'Ursula K. Le Guin', 'genre': 'Science Fiction', 'category': 'Philosophy', 'price': 14.99, 'rating': 4.4, 'stock': 25, 'description': 'A journey to a planet with gender fluidity.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1488213619i/18423.jpg'},
    {'title': 'The Dispossessed', 'author': 'Ursula K. Le Guin', 'genre': 'Science Fiction', 'category': 'Philosophy', 'price': 16.99, 'rating': 4.5, 'stock': 20, 'description': 'An anarchist society on a moon.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1353467455i/13651.jpg'},
    {'title': 'The Road', 'author': 'Cormac McCarthy', 'genre': 'Fiction', 'category': 'Post-Apocalyptic', 'price': 15.99, 'rating': 4.2, 'stock': 40, 'description': 'A father and son journey in a post-apocalyptic world.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1439197219i/6288.jpg'},
    {'title': 'No Country for Old Men', 'author': 'Cormac McCarthy', 'genre': 'Fiction', 'category': 'Thriller', 'price': 14.99, 'rating': 4.3, 'stock': 35, 'description': 'A tale of violence and pursuit.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511302904i/1869.jpg'},
    {'title': 'Blood Meridian', 'author': 'Cormac McCarthy', 'genre': 'Fiction', 'category': 'Western', 'price': 17.99, 'rating': 4.1, 'stock': 25, 'description': 'A violent tale of the American Southwest.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554220401i/394535.jpg'},
    {'title': 'The Goldfinch', 'author': 'Donna Tartt', 'genre': 'Fiction', 'category': 'Drama', 'price': 18.99, 'rating': 4.4, 'stock': 30, 'description': 'A young boy\'s life after a tragedy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1378710146i/17333223.jpg'},
    {'title': 'The Secret History', 'author': 'Donna Tartt', 'genre': 'Fiction', 'category': 'Thriller', 'price': 16.99, 'rating': 4.5, 'stock': 40, 'description': 'A group of classics students commit murder.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1451554846i/29044.jpg'},
    {'title': 'The Little Prince', 'author': 'Antoine de Saint-Exupéry', 'genre': 'Fiction', 'category': 'Children', 'price': 10.99, 'rating': 4.7, 'stock': 60, 'description': 'A philosophical tale for children.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993.jpg'},
    {'title': 'The Old Man and the Sea', 'author': 'Ernest Hemingway', 'genre': 'Fiction', 'category': 'Adventure', 'price': 11.99, 'rating': 4.3, 'stock': 45, 'description': 'An old fisherman\'s struggle with a giant marlin.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1329189714i/2165.jpg'},
    {'title': 'A Farewell to Arms', 'author': 'Ernest Hemingway', 'genre': 'Fiction', 'category': 'Romance', 'price': 13.99, 'rating': 4.2, 'stock': 35, 'description': 'A love story set during World War I.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1313714836i/10799.jpg'},
    {'title': 'The Sun Also Rises', 'author': 'Ernest Hemingway', 'genre': 'Fiction', 'category': 'Classic', 'price': 12.99, 'rating': 4.1, 'stock': 30, 'description': 'The Lost Generation in Europe.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1331828979i/3876.jpg'},
    {'title': 'Slaughterhouse-Five', 'author': 'Kurt Vonnegut', 'genre': 'Science Fiction', 'category': 'War', 'price': 14.99, 'rating': 4.4, 'stock': 40, 'description': 'Billy Pilgrim\'s time-traveling experiences.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1440319389i/4981.jpg'},
    {'title': 'Cat\'s Cradle', 'author': 'Kurt Vonnegut', 'genre': 'Science Fiction', 'category': 'Satire', 'price': 13.99, 'rating': 4.3, 'stock': 35, 'description': 'A satirical novel about science and religion.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327867150i/135479.jpg'},
    {'title': 'Breakfast of Champions', 'author': 'Kurt Vonnegut', 'genre': 'Fiction', 'category': 'Satire', 'price': 15.99, 'rating': 4.2, 'stock': 25, 'description': 'A journey through America.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327340161i/4980.jpg'},
    {'title': 'The Handmaid\'s Tale', 'author': 'Margaret Atwood', 'genre': 'Dystopian', 'category': 'Feminism', 'price': 14.99, 'rating': 4.5, 'stock': 50, 'description': 'A woman\'s life in a totalitarian society.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578028274i/38447.jpg'},
    {'title': 'Oryx and Crake', 'author': 'Margaret Atwood', 'genre': 'Science Fiction', 'category': 'Dystopian', 'price': 16.99, 'rating': 4.4, 'stock': 30, 'description': 'A post-apocalyptic world created by science.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1494108527i/46756.jpg'},
    {'title': 'The Year of the Witching', 'author': 'Alexis Henderson', 'genre': 'Fantasy', 'category': 'Horror', 'price': 17.99, 'rating': 4.3, 'stock': 20, 'description': 'A dark fantasy in a Puritanical society.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'Mexican Gothic', 'author': 'Silvia Moreno-Garcia', 'genre': 'Horror', 'category': 'Gothic', 'price': 15.99, 'rating': 4.4, 'stock': 35, 'description': 'A young woman investigates her cousin\'s mysterious letter.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190236i/53141581.jpg'},
    {'title': 'The Invisible Life of Addie LaRue', 'author': 'V.E. Schwab', 'genre': 'Fantasy', 'category': 'Romance', 'price': 18.99, 'rating': 4.6, 'stock': 40, 'description': 'A woman makes a Faustian bargain to live forever.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'City of Brass', 'author': 'S.A. Chakraborty', 'genre': 'Fantasy', 'category': 'Epic', 'price': 19.99, 'rating': 4.5, 'stock': 30, 'description': 'A djinn and a con woman in a magical city.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1485357965i/32718027.jpg'},
    {'title': 'The City We Became', 'author': 'N.K. Jemisin', 'genre': 'Fantasy', 'category': 'Urban', 'price': 17.99, 'rating': 4.4, 'stock': 25, 'description': 'New York City comes to life as avatars.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/42028597.jpg'},
    {'title': 'The Stone Boatmen', 'author': 'Sarah Tolmie', 'genre': 'Fantasy', 'category': 'Mythology', 'price': 16.99, 'rating': 4.2, 'stock': 20, 'description': 'A retelling of the Argonautica.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554133629i/22328.jpg'},
    {'title': 'The Priory of the Orange Tree', 'author': 'Samantha Shannon', 'genre': 'Fantasy', 'category': 'Epic', 'price': 20.99, 'rating': 4.7, 'stock': 35, 'description': 'Dragons, queens, and ancient prophecies.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1529516205i/40275288.jpg'},
    {'title': 'Gideon the Ninth', 'author': 'Tamsyn Muir', 'genre': 'Science Fiction', 'category': 'Fantasy', 'price': 18.99, 'rating': 4.6, 'stock': 40, 'description': 'A necromancer in space.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546876321i/42036538.jpg'},
    {'title': 'Harrow the Ninth', 'author': 'Tamsyn Muir', 'genre': 'Science Fiction', 'category': 'Fantasy', 'price': 19.99, 'rating': 4.5, 'stock': 30, 'description': 'The second book in the Locked Tomb series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'A Memory Called Empire', 'author': 'Arkady Martine', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 17.99, 'rating': 4.4, 'stock': 25, 'description': 'Diplomacy and intrigue in space.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190253i/52578297.jpg'},
    {'title': 'A Desolation Called Peace', 'author': 'Arkady Martine', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 18.99, 'rating': 4.5, 'stock': 20, 'description': 'The sequel to A Memory Called Empire.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg'},
    {'title': 'The Long Way to a Small, Angry Planet', 'author': 'Becky Chambers', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 16.99, 'rating': 4.6, 'stock': 45, 'description': 'A crew on a long space journey.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1405532476i/22733729.jpg'},
    {'title': 'A Closed and Common Orbit', 'author': 'Becky Chambers', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 17.99, 'rating': 4.5, 'stock': 35, 'description': 'The story of Sidra and Pepper.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1485357965i/32718027.jpg'},
    {'title': 'Record of a Spaceborn Few', 'author': 'Becky Chambers', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 18.99, 'rating': 4.4, 'stock': 30, 'description': 'Life on a generation ship.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546876321i/42036538.jpg'},
    {'title': 'The Calculating Stars', 'author': 'Mary Robinette Kowal', 'genre': 'Science Fiction', 'category': 'Alternate History', 'price': 15.99, 'rating': 4.3, 'stock': 40, 'description': 'Women in space after a meteor strike.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554133629i/22328.jpg'},
    {'title': 'The Fated Stars', 'author': 'Mary Robinette Kowal', 'genre': 'Science Fiction', 'category': 'Alternate History', 'price': 16.99, 'rating': 4.4, 'stock': 35, 'description': 'The sequel to The Calculating Stars.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190236i/53141581.jpg'},
    {'title': 'The Relentless Moon', 'author': 'Mary Robinette Kowal', 'genre': 'Science Fiction', 'category': 'Alternate History', 'price': 17.99, 'rating': 4.5, 'stock': 25, 'description': 'The third book in the Lady Astronaut series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'Ancillary Justice', 'author': 'Ann Leckie', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 14.99, 'rating': 4.5, 'stock': 50, 'description': 'A spaceship AI seeks justice.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1415564163i/17333324.jpg'},
    {'title': 'Ancillary Sword', 'author': 'Ann Leckie', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 15.99, 'rating': 4.4, 'stock': 40, 'description': 'The second book in the Imperial Radch trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1439197219i/6288.jpg'},
    {'title': 'Ancillary Mercy', 'author': 'Ann Leckie', 'genre': 'Science Fiction', 'category': 'Space Opera', 'price': 16.99, 'rating': 4.6, 'stock': 35, 'description': 'The conclusion of the trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511302904i/1869.jpg'},
    {'title': 'The Three-Body Problem', 'author': 'Cixin Liu', 'genre': 'Science Fiction', 'category': 'Hard SF', 'price': 19.99, 'rating': 4.7, 'stock': 30, 'description': 'First contact with an alien civilization.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1410841833i/20518872.jpg'},
    {'title': 'The Dark Forest', 'author': 'Cixin Liu', 'genre': 'Science Fiction', 'category': 'Hard SF', 'price': 20.99, 'rating': 4.6, 'stock': 25, 'description': 'The second book in the trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1456544347i/23168817.jpg'},
    {'title': 'Death\'s End', 'author': 'Cixin Liu', 'genre': 'Science Fiction', 'category': 'Hard SF', 'price': 21.99, 'rating': 4.8, 'stock': 20, 'description': 'The epic conclusion.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1481985247i/25451264.jpg'},
    {'title': 'The Poppy War', 'author': 'R.F. Kuang', 'genre': 'Fantasy', 'category': 'War', 'price': 18.99, 'rating': 4.5, 'stock': 40, 'description': 'A young woman rises to power in a war-torn land.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1544468310i/35068705.jpg'},
    {'title': 'The Dragon Republic', 'author': 'R.F. Kuang', 'genre': 'Fantasy', 'category': 'War', 'price': 19.99, 'rating': 4.6, 'stock': 35, 'description': 'The second book in the Poppy War trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578028274i/38447.jpg'},
    {'title': 'The Burning God', 'author': 'R.F. Kuang', 'genre': 'Fantasy', 'category': 'War', 'price': 20.99, 'rating': 4.7, 'stock': 30, 'description': 'The final book in the trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1494108527i/46756.jpg'},
    {'title': 'The Night Circus', 'author': 'Erin Morgenstern', 'genre': 'Fantasy', 'category': 'Romance', 'price': 16.99, 'rating': 4.4, 'stock': 45, 'description': 'A magical competition between illusionists.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1387124618i/9361589.jpg'},
    {'title': 'The Starless Sea', 'author': 'Erin Morgenstern', 'genre': 'Fantasy', 'category': 'Adventure', 'price': 17.99, 'rating': 4.3, 'stock': 40, 'description': 'A graduate student discovers a secret underground world.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'Uprooted', 'author': 'Naomi Novik', 'genre': 'Fantasy', 'category': 'Fairy Tale', 'price': 15.99, 'rating': 4.5, 'stock': 50, 'description': 'A young woman is chosen by a wizard.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386807454i/22544764.jpg'},
    {'title': 'Spinning Silver', 'author': 'Naomi Novik', 'genre': 'Fantasy', 'category': 'Fairy Tale', 'price': 16.99, 'rating': 4.6, 'stock': 45, 'description': 'Three young women face a dark force.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1500930947i/9969571.jpg'},
    {'title': 'A Court of Thorns and Roses', 'author': 'Sarah J. Maas', 'genre': 'Fantasy', 'category': 'Romance', 'price': 14.99, 'rating': 4.7, 'stock': 60, 'description': 'A huntress kills a faerie and faces consequences.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546409607i/50659467.jpg'},
    {'title': 'A Court of Mist and Fury', 'author': 'Sarah J. Maas', 'genre': 'Fantasy', 'category': 'Romance', 'price': 15.99, 'rating': 4.8, 'stock': 55, 'description': 'The second book in the A Court of Thorns and Roses series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1520269036i/50659468.jpg'},
    {'title': 'A Court of Wings and Ruin', 'author': 'Sarah J. Maas', 'genre': 'Fantasy', 'category': 'Romance', 'price': 16.99, 'rating': 4.9, 'stock': 50, 'description': 'The third book in the series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1529516205i/40275288.jpg'},
    {'title': 'Throne of Glass', 'author': 'Sarah J. Maas', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 13.99, 'rating': 4.6, 'stock': 40, 'description': 'A teenage assassin competes in a deadly tournament.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546409607i/50659467.jpg'},
    {'title': 'Crescent City', 'author': 'Sarah J. Maas', 'genre': 'Fantasy', 'category': 'Urban', 'price': 17.99, 'rating': 4.7, 'stock': 35, 'description': 'Bryce Quinlan seeks justice for her friend\'s murder.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'House of Earth and Blood', 'author': 'Sarah J. Maas', 'genre': 'Fantasy', 'category': 'Urban', 'price': 18.99, 'rating': 4.8, 'stock': 30, 'description': 'The first book in the Crescent City series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190253i/52578297.jpg'},
    {'title': 'The Cruel Prince', 'author': 'Holly Black', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 12.99, 'rating': 4.5, 'stock': 45, 'description': 'Jude Duarte navigates faerie politics.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578939317i/26032825.jpg'},
    {'title': 'The Wicked King', 'author': 'Holly Black', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 13.99, 'rating': 4.6, 'stock': 40, 'description': 'The second book in the Folk of the Air trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1584633432i/53241581.jpg'},
    {'title': 'The Queen of Nothing', 'author': 'Holly Black', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 14.99, 'rating': 4.7, 'stock': 35, 'description': 'The conclusion of the trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg'},
    {'title': 'Six of Crows', 'author': 'Leigh Bardugo', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 15.99, 'rating': 4.8, 'stock': 50, 'description': 'A heist in a gritty fantasy world.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1459349347i/23437156.jpg'},
    {'title': 'Crooked Kingdom', 'author': 'Leigh Bardugo', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 16.99, 'rating': 4.9, 'stock': 45, 'description': 'The sequel to Six of Crows.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1459349356i/22299763.jpg'},
    {'title': 'Shadow and Bone', 'author': 'Leigh Bardugo', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 14.99, 'rating': 4.6, 'stock': 40, 'description': 'Alina Starkov discovers her power.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1339533695i/10194157.jpg'},
    {'title': 'Siege and Storm', 'author': 'Leigh Bardugo', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 15.99, 'rating': 4.7, 'stock': 35, 'description': 'The second book in the Grishaverse.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1358347135i/14061955.jpg'},
    {'title': 'Ruin and Rising', 'author': 'Leigh Bardugo', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 16.99, 'rating': 4.8, 'stock': 30, 'description': 'The final book in the trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1378720108i/14061957.jpg'},
    {'title': 'The Raven Boys', 'author': 'Maggie Stiefvater', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 13.99, 'rating': 4.4, 'stock': 40, 'description': 'A group of teens search for a sleeping Welsh king.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'The Dream Thieves', 'author': 'Maggie Stiefvater', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 14.99, 'rating': 4.5, 'stock': 35, 'description': 'The second book in the Raven Cycle.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'Blue Lily, Lily Blue', 'author': 'Maggie Stiefvater', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 15.99, 'rating': 4.6, 'stock': 30, 'description': 'The third book in the series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'The Raven King', 'author': 'Maggie Stiefvater', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 16.99, 'rating': 4.7, 'stock': 25, 'description': 'The conclusion of the Raven Cycle.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'Red Queen', 'author': 'Victoria Aveyard', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 12.99, 'rating': 4.3, 'stock': 45, 'description': 'Mare Barrow discovers she has powers.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1449778910i/22328546.jpg'},
    {'title': 'Glass Sword', 'author': 'Victoria Aveyard', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 13.99, 'rating': 4.4, 'stock': 40, 'description': 'The second book in the Red Queen series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'King\'s Cage', 'author': 'Victoria Aveyard', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 14.99, 'rating': 4.5, 'stock': 35, 'description': 'The third book in the series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'War Storm', 'author': 'Victoria Aveyard', 'genre': 'Fantasy', 'category': 'Young Adult', 'price': 15.99, 'rating': 4.6, 'stock': 30, 'description': 'The final book in the Red Queen series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1454942834i/17675462.jpg'},
    {'title': 'Divergent', 'author': 'Veronica Roth', 'genre': 'Science Fiction', 'category': 'Young Adult', 'price': 11.99, 'rating': 4.2, 'stock': 50, 'description': 'Tris Prior chooses her faction.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328469514i/13335037.jpg'},
    {'title': 'Insurgent', 'author': 'Veronica Roth', 'genre': 'Science Fiction', 'category': 'Young Adult', 'price': 12.99, 'rating': 4.3, 'stock': 45, 'description': 'The second book in the Divergent series.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328469514i/13335037.jpg'},
    {'title': 'Allegiant', 'author': 'Veronica Roth', 'genre': 'Science Fiction', 'category': 'Young Adult', 'price': 13.99, 'rating': 4.4, 'stock': 40, 'description': 'The conclusion of the trilogy.', 'cover_image_url': 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328469514i/13335037.jpg'},
]

for book_data in books_data:
    book, created = Book.objects.get_or_create(
        title=book_data['title'],
        defaults=book_data
    )
    if created:
        logger.info(f"Created new book: {book.title}")
    else:
        logger.info(f"Book already exists: {book.title}")

logger.info('Sample books created successfully!')
