from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.book_list, name='book_list'),
    path('authors/', views.authors_list, name='authors'),
    path('categories/', views.categories_list, name='categories'),
    path('genres/', views.genres_list, name='genres'),
    path('books/<int:pk>/', views.book_detail, name='book_detail'),
    path('books/<int:pk>/add-review/', views.add_review, name='add_review'),
    path('book-club/', views.book_club, name='book_club'),
    path('book-club/post/<int:pk>/', views.post_detail, name='post_detail'),
    path('book-club/create-post/', views.create_post, name='create_post'),
    path('book-club/post/<int:post_id>/comment/', views.create_comment, name='create_comment'),
    path('book-club/post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('book-club/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-cart/<int:pk>/', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('buy-now/<int:pk>/', views.buy_now, name='buy_now'),
    path('add-to-wishlist/<int:pk>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:pk>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('top-books/', views.top_books, name='top_books'),

    # API endpoints
    path('api/books/', views.api_book_list, name='api_book_list'),
    path('api/recommendations/', views.api_recommendations, name='api_recommendations'),
    path('api/chatbot/', views.api_chatbot, name='api_chatbot'),
    path('api/rag-chat/', views.api_rag_chat, name='api_rag_chat'),
    path('api/chat-messages/', views.api_chat_messages, name='api_chat_messages'),
    path('api/send-chat-message/', views.api_send_chat_message, name='api_send_chat_message'),
    path('api/visual-search/', views.api_visual_search, name='api_visual_search'),
    path('api/book/<int:pk>/', views.api_book_detail, name='api_book_detail'),
    path('api/process-payment/', views.api_process_payment, name='api_process_payment'),
    path('api/payment/webhook/', views.api_payment_webhook, name='api_payment_webhook'),
    path('api/welcome/', views.api_welcome, name='api_welcome'),

    # User book selling URLs
    path('sell-book/', views.sell_book, name='sell_book'),
    path('my-listings/', views.my_listings, name='my_listings'),
    path('edit-listing/<int:pk>/', views.edit_listing, name='edit_listing'),
    path('delete-listing/<int:pk>/', views.delete_listing, name='delete_listing'),
    path('buy-user-book/<int:pk>/', views.buy_user_book, name='buy_user_book'),
    path('user-book/<int:pk>/', views.user_book_detail, name='user_book_detail'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('add-to-comparison/<int:pk>/', views.add_to_comparison, name='add_to_comparison'),
    path('remove-from-comparison/<int:pk>/', views.remove_from_comparison, name='remove_from_comparison'),
    path('comparison/', views.comparison, name='comparison'),
    path('clear-comparison/', views.clear_comparison, name='clear_comparison'),
    path('rate-seller/<int:user_book_id>/', views.rate_seller, name='rate_seller'),
    # Help Center static pages
    path('help/', views.help_center, name='help_center'),
    path('help/shipping-info/', views.shipping_info, name='shipping_info'),
    path('help/returns/', views.returns_info, name='returns_info'),
    path('help/track-order/', views.track_order, name='track_order'),
    path('help/contact-us/', views.contact_us, name='contact_us'),
]
