# Generated by Django 4.2.1 on 2025-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_userbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
