# Generated by Django 4.2.1 on 2025-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_book_cover_image_book_cover_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userbook",
            name="image_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
