# Generated by Django 4.2.1 on 2025-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_order_delivery_date_order_shipping_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_features",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbook",
            name="image_features",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
