# Generated by Django 4.2.1 on 2025-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_book_is_featured_book_original_price_book_total_sold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
    ]
