# Generated by Django 4.2.1 on 2025-11-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_orderstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
